const TITULOS=`Moby Dick|The Art of War|Pride and Prejudice|The Hobbit|1984|One Hundred Years of Solitude|The Little Prince|The Catcher in the Rye|To Kill a Mockingbird|The Great Gatsby|Brave New World|The Alchemist|Crime and Punishment|The Brothers Karamazov|War and Peace|Anna Karenina|Don Quixote|Hamlet|Macbeth|The Odyssey|The Iliad|Frankenstein|Dracula|Jane Eyre|Wuthering Heights|The Picture of Dorian Gray|The Trial|The Metamorphosis|The Stranger|The Old Man and the Sea|The Grapes of Wrath|Fahrenheit 451|Dune|Foundation|The Name of the Rose|The Master and Margarita|The Handmaid's Tale|Beloved|Invisible Man|The Color Purple|The Road|Never Let Me Go|The Remains of the Day|Norwegian Wood|Blindness|The Book Thief|The Shadow of the Wind|The Unbearable Lightness of Being|Things Fall Apart|Siddhartha|Alice's Adventures in Wonderland|The Adventures of Sherlock Holmes|Treasure Island|The Secret Garden|Little Women|Anne of Green Gables|A Tale of Two Cities|Great Expectations|David Copperfield|Oliver Twist|The Count of Monte Cristo|The Three Musketeers|The Scarlet Letter|The Call of the Wild|White Fang|The Jungle Book|The Wind in the Willows|The Wonderful Wizard of Oz|The Time Machine|The War of the Worlds|The Invisible Man|A Room with a View|The Awakening|The Yellow Wallpaper|The Souls of Black Folk|Dom Casmurro|Os Lusíadas|A Illustre Casa de Ramires|Poesias|As Minas de Salomão|O Olho de Vidro|A Lenda da Meia-Noite|Pátria|A correspondência de Fradique Mendes: memórias e notas|Novelas do Minho|Viriatho: Narrativa epo-historica|A Morte Vence|Nova Sapho: Tragedia Extranha|The Adventures of Tom Sawyer|The Adventures of Huckleberry Finn|The Raven|Ozymandias|If—|A Modest Proposal|Gettysburg Address|United States Declaration of Independence|Sonnet 18|Invictus|Jabberwocky|The New Colossus`.split('|');
const normalizar=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’‘`´]/g,"'").replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const palavras=s=>normalizar(s).split(' ').filter(x=>x.length>1);
const bate=(alvo,candidatos)=>{const a=normalizar(alvo),pa=palavras(alvo);return candidatos.some(c=>{const n=normalizar(c);if(!n)return false;if(n===a||n.includes(a)||a.includes(n))return true;const pc=new Set(palavras(c));return pa.length&&pa.filter(x=>pc.has(x)).length/pa.length>=.75})};
const espera=ms=>new Promise(r=>setTimeout(r,ms));
async function json(url,tentativas=5){let erro;for(let i=0;i<tentativas;i++){try{const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'BibliotecaLivre-QA/1.0'},signal:AbortSignal.timeout(14000)});let d=null;try{d=await r.json()}catch{}if(r.ok)return d??{};erro=new Error(`${r.status} ${r.statusText}`);erro.status=r.status;if(![408,425,429,500,502,503,504].includes(r.status))throw erro;const ra=Number(r.headers.get('retry-after'));if(i<tentativas-1)await espera(Number.isFinite(ra)&&ra>0?Math.min(ra*1000,5000):650*(i+1));continue}catch(e){erro=e;if(i<tentativas-1)await espera(650*(i+1))}}throw erro}
async function openlibrary(t){for(const modo of ['title','q']){const u=new URL('https://openlibrary.org/search.json');u.searchParams.set(modo,t);u.searchParams.set('limit','50');u.searchParams.set('fields','title,author_name,key');try{const d=await json(u);if(bate(t,(d.docs||[]).map(x=>x.title||'')))return true}catch{}}return false}
async function gutendex(t){for(const q of [t,normalizar(t)]){const u=new URL('https://gutendex.com/books/');u.searchParams.set('search',q);try{const d=await json(u);if(bate(t,(d.results||[]).map(x=>x.title||'')))return true}catch{}}return false}
async function wiki(t){for(const base of ['https://en.wikisource.org','https://pt.wikisource.org','https://es.wikisource.org','https://fr.wikisource.org']){const u=new URL(base+'/w/api.php');for(const [k,v] of Object.entries({action:'query',list:'search',srsearch:`intitle:\"${t.replace(/\"/g,' ')}\"`,srnamespace:'0',srlimit:'20',format:'json',origin:'*'}))u.searchParams.set(k,v);try{const d=await json(u,3);if(bate(t,(d.query?.search||[]).map(x=>x.title||'')))return true}catch{}}return false}
let googleDisponivel=true;
async function google(t){if(!googleDisponivel)return false;for(const q of [`intitle:\"${t.replace(/\"/g,' ')}\"`,t]){const u=new URL('https://www.googleapis.com/books/v1/volumes');u.searchParams.set('q',q);u.searchParams.set('maxResults','40');u.searchParams.set('printType','books');try{const d=await json(u,2);if(bate(t,(d.items||[]).map(x=>x.volumeInfo?.title||'')))return true}catch(e){if(e?.status===429||e?.status===403){googleDisponivel=false;console.log('INFO Google Books indisponível neste runner por quota/IP; fallbacks continuam.');return false}}}return false}
const contagem={google:0,openlibrary:0,gutenberg:0,wikisource:0};
async function testar(t,i){const [g,o,gu]=await Promise.all([google(t),openlibrary(t),gutendex(t)]);const fontes=[];if(g){fontes.push('google');contagem.google++}if(o){fontes.push('openlibrary');contagem.openlibrary++}if(gu){fontes.push('gutenberg');contagem.gutenberg++}if(!fontes.length){const w=await wiki(t);if(w){fontes.push('wikisource');contagem.wikisource++}}const ok=fontes.length>0;console.log(`${String(i+1).padStart(3,'0')}/100 ${ok?'PASS':'FAIL'} ${t} [${fontes.join(', ')}]`);return{t,ok,fontes}}
const resultados=[];for(let i=0;i<TITULOS.length;i+=3){const lote=TITULOS.slice(i,i+3);const r=await Promise.all(lote.map((t,j)=>testar(t,i+j)));resultados.push(...r);await espera(350)}
const falhas=resultados.filter(x=>!x.ok);console.log('\nFONTES:',contagem);console.log(`RESULTADO: ${100-falhas.length}/100`);if(falhas.length){console.log('FALHAS:',JSON.stringify(falhas,null,2));process.exit(1)}
