const normalizar=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const palavras=s=>normalizar(s).split(/\s+/).filter(x=>x.length>1);
const corresponde=(alvo,candidatos)=>{const a=normalizar(alvo),pa=palavras(alvo);return candidatos.some(c=>{const n=normalizar(c);if(!n)return false;if(n===a||n.includes(a)||a.includes(n))return true;const pc=new Set(palavras(c));return pa.length>0&&pa.filter(x=>pc.has(x)).length/pa.length>=.75})};
const espera=ms=>new Promise(r=>setTimeout(r,ms));
async function json(url,opcoes={},tentativas=3){let e;for(let i=0;i<tentativas;i++){try{const r=await fetch(url,{...opcoes,headers:{Accept:'application/json','User-Agent':'BibliotecaLivre-QA/1.0',...(opcoes.headers||{})}});if(r.ok)return await r.json();e=new Error(`${r.status} ${r.statusText}`)}catch(err){e=err}await espera(500*(i+1))}throw e}
async function google(t){const u=new URL('https://www.googleapis.com/books/v1/volumes');u.searchParams.set('q',`${t.titulo} ${t.autor||''}`.trim());u.searchParams.set('maxResults','20');u.searchParams.set('printType','books');u.searchParams.set('orderBy','relevance');const d=await json(u);return corresponde(t.titulo,(d.items||[]).map(x=>x.volumeInfo?.title||''))}
async function openlibrary(t){const u=new URL('https://openlibrary.org/search.json');u.searchParams.set('title',t.titulo);if(t.autor)u.searchParams.set('author',t.autor);u.searchParams.set('limit','20');u.searchParams.set('fields','title,author_name,key');const d=await json(u);return corresponde(t.titulo,(d.docs||[]).map(x=>x.title||''))}
async function gutendex(t){const u=new URL('https://gutendex.com/books/');u.searchParams.set('search',t.titulo);const d=await json(u);return corresponde(t.titulo,(d.results||[]).map(x=>x.title||''))}
async function wiki(t){const bases=['https://en.wikisource.org','https://pt.wikisource.org','https://es.wikisource.org','https://fr.wikisource.org'];for(const base of bases){const u=new URL(base+'/w/api.php');u.searchParams.set('action','query');u.searchParams.set('list','search');u.searchParams.set('srsearch',`intitle:"${t.titulo.replace(/"/g,' ')}"`);u.searchParams.set('srnamespace','0');u.searchParams.set('srlimit','10');u.searchParams.set('format','json');u.searchParams.set('origin','*');try{const d=await json(u);if(corresponde(t.titulo,(d.query?.search||[]).map(x=>x.title||'')))return true}catch{}}return false}
const testes=[
['google','Moby Dick','Herman Melville'],['google','The Art of War','Sun Tzu'],['google','Pride and Prejudice','Jane Austen'],['google','The Hobbit','J. R. R. Tolkien'],['google','1984','George Orwell'],['google','One Hundred Years of Solitude','Gabriel Garcia Marquez'],['google','The Little Prince','Antoine de Saint-Exupery'],['google','The Catcher in the Rye','J. D. Salinger'],['google','To Kill a Mockingbird','Harper Lee'],['google','The Great Gatsby','F. Scott Fitzgerald'],['google','Brave New World','Aldous Huxley'],['google','The Alchemist','Paulo Coelho'],['google','Crime and Punishment','Fyodor Dostoevsky'],['google','The Brothers Karamazov','Fyodor Dostoevsky'],['google','War and Peace','Leo Tolstoy'],['google','Anna Karenina','Leo Tolstoy'],['google','Don Quixote','Miguel de Cervantes'],['google','Hamlet','William Shakespeare'],['google','Macbeth','William Shakespeare'],['google','The Odyssey','Homer'],['google','The Iliad','Homer'],['google','Frankenstein','Mary Shelley'],['google','Dracula','Bram Stoker'],['google','Jane Eyre','Charlotte Bronte'],['google','Wuthering Heights','Emily Bronte'],['google','The Picture of Dorian Gray','Oscar Wilde'],['google','The Trial','Franz Kafka'],['google','The Metamorphosis','Franz Kafka'],['google','The Stranger','Albert Camus'],['google','The Old Man and the Sea','Ernest Hemingway'],['google','The Grapes of Wrath','John Steinbeck'],['google','Fahrenheit 451','Ray Bradbury'],['google','Dune','Frank Herbert'],['google','Foundation','Isaac Asimov'],['google','The Name of the Rose','Umberto Eco'],['google','The Master and Margarita','Mikhail Bulgakov'],['google','The Handmaid\'s Tale','Margaret Atwood'],['google','Beloved','Toni Morrison'],['google','Invisible Man','Ralph Ellison'],['google','The Color Purple','Alice Walker'],['google','The Road','Cormac McCarthy'],['google','Never Let Me Go','Kazuo Ishiguro'],['google','The Remains of the Day','Kazuo Ishiguro'],['google','Norwegian Wood','Haruki Murakami'],['google','Blindness','Jose Saramago'],['google','The Book Thief','Markus Zusak'],['google','The Shadow of the Wind','Carlos Ruiz Zafon'],['google','The Unbearable Lightness of Being','Milan Kundera'],['google','Things Fall Apart','Chinua Achebe'],['google','Siddhartha','Hermann Hesse'],
['openlibrary','Alice\'s Adventures in Wonderland','Lewis Carroll'],['openlibrary','The Adventures of Sherlock Holmes','Arthur Conan Doyle'],['openlibrary','Treasure Island','Robert Louis Stevenson'],['openlibrary','The Secret Garden','Frances Hodgson Burnett'],['openlibrary','Little Women','Louisa May Alcott'],['openlibrary','Anne of Green Gables','L. M. Montgomery'],['openlibrary','A Tale of Two Cities','Charles Dickens'],['openlibrary','Great Expectations','Charles Dickens'],['openlibrary','David Copperfield','Charles Dickens'],['openlibrary','Oliver Twist','Charles Dickens'],['openlibrary','The Count of Monte Cristo','Alexandre Dumas'],['openlibrary','The Three Musketeers','Alexandre Dumas'],['openlibrary','The Scarlet Letter','Nathaniel Hawthorne'],['openlibrary','The Call of the Wild','Jack London'],['openlibrary','White Fang','Jack London'],['openlibrary','The Jungle Book','Rudyard Kipling'],['openlibrary','The Wind in the Willows','Kenneth Grahame'],['openlibrary','The Wonderful Wizard of Oz','L. Frank Baum'],['openlibrary','The Time Machine','H. G. Wells'],['openlibrary','The War of the Worlds','H. G. Wells'],['openlibrary','The Invisible Man','H. G. Wells'],['openlibrary','A Room with a View','E. M. Forster'],['openlibrary','The Awakening','Kate Chopin'],['openlibrary','The Yellow Wallpaper','Charlotte Perkins Gilman'],['openlibrary','The Souls of Black Folk','W. E. B. Du Bois'],
['gutendex','Dom Casmurro','Machado de Assis'],['gutendex','Os Lusíadas','Luís de Camões'],['gutendex','A Illustre Casa de Ramires','Eça de Queirós'],['gutendex','Poesias','Alexandre Herculano'],['gutendex','As Minas de Salomão','H. Rider Haggard'],['gutendex','O Olho de Vidro','Camilo Castelo Branco'],['gutendex','A Lenda da Meia-Noite','Manuel Pinheiro Chagas'],['gutendex','Pátria','Guerra Junqueiro'],['gutendex','A correspondência de Fradique Mendes: memórias e notas','Eça de Queirós'],['gutendex','Novelas do Minho','Camilo Castelo Branco'],['gutendex','Viriatho: Narrativa epo-historica','Teófilo Braga'],['gutendex','A Morte Vence','João Grave'],['gutendex','Nova Sapho: Tragedia Extranha','Bento de Oliveira Cardoso'],['gutendex','The Adventures of Tom Sawyer','Mark Twain'],['gutendex','The Adventures of Huckleberry Finn','Mark Twain'],
['wiki','The Raven','Edgar Allan Poe'],['wiki','Ozymandias','Percy Bysshe Shelley'],['wiki','If—','Rudyard Kipling'],['wiki','A Modest Proposal','Jonathan Swift'],['wiki','Gettysburg Address','Abraham Lincoln'],['wiki','United States Declaration of Independence','Thomas Jefferson'],['wiki','Sonnet 18','William Shakespeare'],['wiki','Invictus','William Ernest Henley'],['wiki','Jabberwocky','Lewis Carroll'],['wiki','The New Colossus','Emma Lazarus']
].map(([fonte,titulo,autor])=>({fonte,titulo,autor}));
const funcoes={google,openlibrary,gutendex,wiki};let passou=0;const falhas=[];
for(let i=0;i<testes.length;i++){const t=testes[i];let ok=false,erro='';try{ok=await funcoes[t.fonte](t)}catch(e){erro=e?.message||String(e)}if(ok)passou++;else falhas.push({...t,erro});console.log(`${String(i+1).padStart(3,'0')}/100 ${ok?'PASS':'FAIL'} [${t.fonte}] ${t.titulo}${erro?' — '+erro:''}`);if(t.fonte==='openlibrary')await espera(1100);else await espera(180)}
console.log(`\nRESULTADO: ${passou}/100`);if(falhas.length){console.log('FALHAS:',JSON.stringify(falhas,null,2));process.exit(1)}
