const limpar=v=>String(v||'').replace(/[<>\u0000-\u001f]/g,' ').replace(/\s+/g,' ').trim().slice(0,160);
const semAcento=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const textoHtml=v=>String(v||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/\s+/g,' ').trim();
const seguroUrl=(valor,base)=>{try{const u=new URL(valor,base);return['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}};
const mapa={
 'mandarim':{nome:'Mandarim',busca:'Mandarin Chinese',fsi:'chinese',coerll:'chinese',live:'chinese/mandarin'},'chines':{nome:'Chinês',busca:'Chinese',fsi:'chinese',coerll:'chinese',live:'chinese/mandarin'},'chinês':{nome:'Chinês',busca:'Chinese',fsi:'chinese',coerll:'chinese',live:'chinese/mandarin'},
 'japones':{nome:'Japonês',busca:'Japanese',fsi:'japanese',coerll:'japanese',live:'japanese'},'japonês':{nome:'Japonês',busca:'Japanese',fsi:'japanese',coerll:'japanese',live:'japanese'},'coreano':{nome:'Coreano',busca:'Korean',fsi:'korean',coerll:'korean',live:'korean'},
 'arabe':{nome:'Árabe',busca:'Arabic',fsi:'arabic',coerll:'arabic',live:'arabic'},'árabe':{nome:'Árabe',busca:'Arabic',fsi:'arabic',coerll:'arabic',live:'arabic'},'frances':{nome:'Francês',busca:'French',fsi:'french',coerll:'french',live:'french'},'francês':{nome:'Francês',busca:'French',fsi:'french',coerll:'french',live:'french'},
 'espanhol':{nome:'Espanhol',busca:'Spanish',fsi:'spanish',coerll:'spanish',live:'spanish'},'alemao':{nome:'Alemão',busca:'German',fsi:'german',coerll:'german',live:'german'},'alemão':{nome:'Alemão',busca:'German',fsi:'german',coerll:'german',live:'german'},'italiano':{nome:'Italiano',busca:'Italian',fsi:'italian',coerll:'italian',live:'italian'},
 'portugues':{nome:'Português',busca:'Portuguese',fsi:'portuguese',coerll:'portuguese',live:'portuguese'},'português':{nome:'Português',busca:'Portuguese',fsi:'portuguese',coerll:'portuguese',live:'portuguese'},'russo':{nome:'Russo',busca:'Russian',fsi:'russian',coerll:'russian',live:'russian'},'hindi':{nome:'Hindi',busca:'Hindi',fsi:'hindi',coerll:'hindi',live:'hindi'},
 'turco':{nome:'Turco',busca:'Turkish',fsi:'turkish',coerll:'turkish',live:'turkish'},'hebraico':{nome:'Hebraico',busca:'Hebrew',fsi:'hebrew',coerll:'hebrew',live:'hebrew'},'grego':{nome:'Grego',busca:'Greek',fsi:'greek',coerll:'greek',live:'greek'},'persa':{nome:'Persa',busca:'Persian Farsi',fsi:'persian',coerll:'persian',live:'persian'},
 'swahili':{nome:'Swahili',busca:'Swahili',fsi:'swahili',coerll:'swahili',live:'swahili'},'suaili':{nome:'Swahili',busca:'Swahili',fsi:'swahili',coerll:'swahili',live:'swahili'},'ioruba':{nome:'Yorùbá',busca:'Yoruba',fsi:'yoruba',coerll:'yoruba',live:'yoruba'},'yoruba':{nome:'Yorùbá',busca:'Yoruba',fsi:'yoruba',coerll:'yoruba',live:'yoruba'},
 'hausa':{nome:'Hausa',busca:'Hausa',fsi:'hausa',coerll:'hausa',live:'hausa'},'tagalog':{nome:'Tagalog',busca:'Tagalog',fsi:'tagalog',coerll:'tagalog',live:'tagalog'},'tailandes':{nome:'Tailandês',busca:'Thai',fsi:'thai',coerll:'thai',live:'thai'},'tailandês':{nome:'Tailandês',busca:'Thai',fsi:'thai',coerll:'thai',live:'thai'},'vietnamita':{nome:'Vietnamita',busca:'Vietnamese',fsi:'vietnamese',coerll:'vietnamese',live:'vietnamese'},
 'quechua':{nome:'Quechua',busca:'Quechua',coerll:'quechua',live:'quechua'},'quichua':{nome:'Quechua',busca:'Quechua',coerll:'quechua',live:'quechua'},'kiche':{nome:"K'iche'",busca:"K'iche'",coerll:'kiche'},'k’iche’':{nome:"K'iche'",busca:"K'iche'",coerll:'kiche'},'zapoteco':{nome:'Zapoteco',busca:'Zapotec',coerll:'zapotec'},
 'latim':{nome:'Latim',busca:'Latin',coerll:'latin'},'nheengatu':{nome:'Nheengatu',busca:'Nheengatu'},'guarani':{nome:'Guarani',busca:'Guarani'}
};
function detectar(q){const n=semAcento(q),chaves=Object.keys(mapa).sort((a,b)=>b.length-a.length);for(const k of chaves)if(n.includes(semAcento(k)))return mapa[k];return{nome:q,busca:q}}
async function obter(url){const r=await fetch(url,{headers:{Accept:'text/html,application/xhtml+xml','User-Agent':'BibliotecaLivre/2.4 (mailto:suporte@bibliotecalivre.org)'},signal:AbortSignal.timeout(6500)});if(!r.ok)throw new Error(String(r.status));return{html:await r.text(),url:r.url||url}}
function tituloDoBloco(bloco){const h=bloco.match(/<h[1-6][^>]*>([\s\S]*?)<\/h[1-6]>/i);const t=textoHtml(h?.[1]||bloco);return t.replace(/^(FSI|DLI|Peace Corps)\s+/i,'').trim().slice(0,180)}
function estatisticas(t){const partes=[];const pdf=t.match(/(\d[\d,.]*)\s*PDF/i);const pag=t.match(/(\d[\d,.]*)\s*pages?/i);const aud=t.match(/(\d[\d,.]*)\s*audio/i);if(pdf)partes.push(`${pdf[1]} PDF${pdf[1]==='1'?'':'s'}`);if(pag)partes.push(`${pag[1]} páginas`);if(aud)partes.push(`${aud[1]} áudios`);return partes.join(' · ')}
async function buscarFsi(info){if(!info.fsi)return[];try{const base=`https://www.fsi-language-courses.org/${encodeURIComponent(info.fsi)}/`,{html,url:baseFinal}=await obter(base),re=/<a\b[^>]*href=["']([^"']*\/courses\/[^"'#?]+\/?)["'][^>]*>([\s\S]*?)<\/a>/gi,vistos=new Set(),saida=[];let m;while((m=re.exec(html))&&saida.length<18){const u=seguroUrl(m[1],baseFinal);if(!u||vistos.has(u))continue;const bruto=textoHtml(m[2]);if(!bruto||!/course|reader|material|program|introduction/i.test(bruto))continue;const titulo=tituloDoBloco(m[2]);if(titulo.length<5)continue;vistos.add(u);const ehDli=/\bDLI\b|Defense Language Institute/i.test(bruto),ehPeace=/Peace Corps/i.test(bruto);saida.push({id:`curso:${Buffer.from(u).toString('base64url').slice(0,46)}`,fonte:ehDli?'dli':'fsi',provedor:ehDli?'Defense Language Institute · FSI Language Courses':ehPeace?'Peace Corps · FSI Language Courses':'Foreign Service Institute · FSI Language Courses',titulo,descricao:estatisticas(bruto)||`Curso gratuito de ${info.nome}.`,tipo:'Curso completo',url:u,modo:'curso',idioma:info.nome,audio:null})}return saida}catch{return[]}}
async function buscarCoerll(info){if(!info.coerll)return[];try{const base=`https://coerll.utexas.edu/coerll/materials/language/${encodeURIComponent(info.coerll)}/`,{html,url:baseFinal}=await obter(base),re=/<a\b[^>]*href=["']([^"']*\/coerll\/oer\/[^"'#?]+\/?)["'][^>]*>([\s\S]*?)<\/a>/gi,vistos=new Set(),saida=[];let m;while((m=re.exec(html))&&saida.length<12){const u=seguroUrl(m[1],baseFinal),titulo=tituloDoBloco(m[2]);if(!u||vistos.has(u)||titulo.length<4||/^go to oer$/i.test(titulo))continue;vistos.add(u);saida.push({id:`coerll:${Buffer.from(u).toString('base64url').slice(0,46)}`,fonte:'coerll',provedor:'COERLL',titulo,descricao:`Recurso educacional aberto para estudo de ${info.nome}.`,tipo:/grammar/i.test(titulo)?'Gramática / exercícios':'Curso / material aberto',url:u,modo:'curso',idioma:info.nome,audio:null})}return saida}catch{return[]}}
async function buscarMerlot(info,q){try{const termo=info.busca||q,u=`https://www.merlot.org/merlot/materials.htm?keywords=${encodeURIComponent(termo)}&sort.property=relevance`,{html,url:baseFinal}=await obter(u),re=/<a\b[^>]*href=["']([^"']*viewMaterial\.htm\?id=\d+[^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi,vistos=new Set(),saida=[];let m;while((m=re.exec(html))&&saida.length<12){const url=seguroUrl(m[1],baseFinal),titulo=tituloDoBloco(m[2]);if(!url||vistos.has(url)||titulo.length<5||/view material|bookmark|review/i.test(titulo))continue;vistos.add(url);saida.push({id:`merlot:${Buffer.from(url).toString('base64url').slice(0,46)}`,fonte:'merlot',provedor:'MERLOT World Languages',titulo,descricao:`Material educacional aberto relacionado a ${info.nome||q}.`,tipo:/textbook|book/i.test(titulo)?'Livro / apostila':'Curso / material aberto',url,modo:'curso',idioma:info.nome||'',audio:null})}return saida}catch{return[]}}
async function buscarLiveLingua(info){if(!info.live)return[];try{const base=`https://www.livelingua.com/project/peace-corps/${info.live}`,{html,url:baseFinal}=await obter(base),re=/<a\b[^>]*href=["']([^"']*\/course\/peace-corps\/[^"'#?]+)["'][^>]*>([\s\S]*?)<\/a>/gi,vistos=new Set(),saida=[];let m;while((m=re.exec(html))&&saida.length<10){const url=seguroUrl(m[1],baseFinal),titulo=tituloDoBloco(m[2]);if(!url||vistos.has(url)||titulo.length<5)continue;vistos.add(url);saida.push({id:`livelingua:${Buffer.from(url).toString('base64url').slice(0,46)}`,fonte:'livelingua',provedor:'Peace Corps / Live Lingua',titulo,descricao:`Curso gratuito com materiais de estudo${/audio/i.test(textoHtml(m[2]))?' e áudio':''}.`,tipo:'Curso completo',url,modo:'curso',idioma:info.nome,audio:null})}return saida}catch{return[]}}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({erro:'Método não permitido.'});const q=limpar(req.query.q);if(!q)return res.status(400).json({erro:'Consulta obrigatória.'});const info=detectar(q),grupos=await Promise.all([buscarFsi(info),buscarCoerll(info),buscarMerlot(info,q),buscarLiveLingua(info)]),resultados=grupos.flat(),porFonte={};for(const id of['fsi','dli','coerll','merlot','livelingua']){const quantidade=resultados.filter(x=>x.fonte===id).length;porFonte[id]={quantidade,portal:false,erro:false}}res.setHeader('Cache-Control','s-maxage=900, stale-while-revalidate=3600');return res.status(200).json({ok:true,consulta:q,resultados,porFonte});}
