const limpar=v=>String(v||'').replace(/[<>\u0000-\u001f]/g,' ').replace(/\s+/g,' ').trim().slice(0,160);
const semAcento=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const textoHtml=v=>String(v||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/\s+/g,' ').trim();
const seguroUrl=(valor,base)=>{try{const u=new URL(valor,base);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}};
const tipos=t=>{const s=semAcento(t);if(/gramat|grammar/.test(s))return'Gramática';if(/dicion|dictionary|lexicon|vocab/.test(s))return'Dicionário / vocabulário';if(/cartilha|workbook|apostila|textbook|manual|livro|book/.test(s))return'Livro / apostila';if(/curso|course|curriculum|lesson|licao|exercise/.test(s))return'Curso / lição';if(/audio|pronunciation|recording|gravac/.test(s))return'Áudio / pronúncia';if(/tese|thesis|dissert|paper|article|estudo/.test(s))return'Estudo / pesquisa';return'Recurso de idioma'};
const idiomas={
 nheengatu:{codigo:'yrl',ingles:'Nheengatu',indigena:true},'lingua geral amazonica':{codigo:'yrl',ingles:'Nheengatu',indigena:true},guarani:{codigo:'grn',ingles:'Guarani',indigena:true},'tupi antigo':{codigo:'tpw',ingles:'Old Tupi',indigena:true},tupi:{codigo:'tpw',ingles:'Tupi',indigena:true},tupinamba:{codigo:'tpn',ingles:'Tupinamba',indigena:true},quechua:{codigo:'que',ingles:'Quechua',indigena:true},quichua:{codigo:'que',ingles:'Quechua',indigena:true},aymara:{codigo:'aym',ingles:'Aymara',indigena:true},mapuche:{codigo:'arn',ingles:'Mapudungun',indigena:true},mapudungun:{codigo:'arn',ingles:'Mapudungun',indigena:true},xavante:{codigo:'xav',ingles:'Xavante',indigena:true},yanomami:{codigo:'guu',ingles:'Yanomami',indigena:true},tikuna:{codigo:'tca',ingles:'Tikuna',indigena:true},ticuna:{codigo:'tca',ingles:'Tikuna',indigena:true},kaingang:{codigo:'kgp',ingles:'Kaingang',indigena:true},terena:{codigo:'ter',ingles:'Terena',indigena:true},baniwa:{codigo:'bwi',ingles:'Baniwa',indigena:true},kaxinawa:{codigo:'cbs',ingles:'Kaxinawa',indigena:true},'huni kuin':{codigo:'cbs',ingles:'Huni Kuin',indigena:true},cherokee:{codigo:'chr',ingles:'Cherokee',indigena:true},navajo:{codigo:'nav',ingles:'Navajo',indigena:true},lakota:{codigo:'lkt',ingles:'Lakota',indigena:true},ojibwe:{codigo:'oji',ingles:'Ojibwe',indigena:true},portugues:{codigo:'por',ingles:'Portuguese'},'português':{codigo:'por',ingles:'Portuguese'},ingles:{codigo:'eng',ingles:'English'},'inglês':{codigo:'eng',ingles:'English'},espanhol:{codigo:'spa',ingles:'Spanish'},frances:{codigo:'fra',ingles:'French'},'francês':{codigo:'fra',ingles:'French'},alemao:{codigo:'deu',ingles:'German'},'alemão':{codigo:'deu',ingles:'German'},italiano:{codigo:'ita',ingles:'Italian'},japones:{codigo:'jpn',ingles:'Japanese'},'japonês':{codigo:'jpn',ingles:'Japanese'},mandarim:{codigo:'cmn',ingles:'Mandarin Chinese'},chines:{codigo:'cmn',ingles:'Chinese'},'chinês':{codigo:'cmn',ingles:'Chinese'},coreano:{codigo:'kor',ingles:'Korean'},arabe:{codigo:'ara',ingles:'Arabic'},'árabe':{codigo:'ara',ingles:'Arabic'},russo:{codigo:'rus',ingles:'Russian'},hindi:{codigo:'hin',ingles:'Hindi'},urdu:{codigo:'urd',ingles:'Urdu'},persa:{codigo:'pes',ingles:'Persian'},turco:{codigo:'tur',ingles:'Turkish'},latim:{codigo:'lat',ingles:'Latin'},grego:{codigo:'ell',ingles:'Greek'},hebraico:{codigo:'heb',ingles:'Hebrew'},swahili:{codigo:'swa',ingles:'Swahili'},suaili:{codigo:'swa',ingles:'Swahili'},ioruba:{codigo:'yor',ingles:'Yoruba'},yoruba:{codigo:'yor',ingles:'Yoruba'},hausa:{codigo:'hau',ingles:'Hausa'},tagalog:{codigo:'tgl',ingles:'Tagalog'},tailandes:{codigo:'tha',ingles:'Thai'},'tailandês':{codigo:'tha',ingles:'Thai'},vietnamita:{codigo:'vie',ingles:'Vietnamese'}
};
function detectarIdioma(q){const n=semAcento(q),chaves=Object.keys(idiomas).sort((a,b)=>b.length-a.length);for(const nome of chaves){const alvo=semAcento(nome);if(new RegExp(`(^|\\b)${alvo.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}(\\b|$)`,'i').test(n)){const info=idiomas[nome],termo=n.replace(alvo,' ').replace(/\s+/g,' ').trim();return{...info,nome,termo}}}return{codigo:null,nome:null,ingles:null,indigena:false,termo:q}}
function termosBusca(q,det){const termos=new Set(semAcento(q).split(/\s+/).filter(x=>x.length>=3));if(det?.ingles)for(const p of semAcento(det.ingles).split(/\s+/))if(p.length>=3)termos.add(p);return[...termos]}
const fontes=[
 {id:'curt',nome:'Biblioteca Digital Curt Nimuendajú',modo:'html',escopo:'indigena',home:'https://www.etnolinguistica.org/',url:q=>`https://www.etnolinguistica.org/search:site/q/${encodeURIComponent(q)}`,descricao:'Livros, gramáticas, cartilhas, dicionários e documentação de línguas indígenas sul-americanas.'},
 {id:'museu',nome:'Museu Nacional dos Povos Indígenas',modo:'html',escopo:'indigena',home:'https://www.gov.br/museudoindio/',url:q=>`https://www.gov.br/museudoindio/pt-br/search?SearchableText=${encodeURIComponent(q)}`,descricao:'Publicações, acervos e materiais oficiais sobre povos e línguas indígenas.'},
 {id:'isa',nome:'Instituto Socioambiental · ISA',modo:'html',escopo:'indigena',home:'https://acervo.socioambiental.org/',url:q=>`https://acervo.socioambiental.org/acervo?search_api_fulltext=${encodeURIComponent(q)}`,descricao:'Livros, estudos, relatórios e documentos sobre povos, culturas e línguas indígenas.'},
 {id:'ailla',nome:'AILLA',modo:'portal',escopo:'indigena',home:'https://ailla.utexas.org/',descricao:'Archive of the Indigenous Languages of Latin America.'},
 {id:'olac',nome:'OLAC',modo:'html',escopo:'geral',home:'https://www.language-archives.org/',url:q=>`https://search.language-archives.org/search.html?q=${encodeURIComponent(q)}`,descricao:'Recursos linguísticos de arquivos do mundo inteiro.'},
 {id:'bdtd',nome:'BDTD / IBICT',modo:'html',escopo:'geral',home:'https://bdtd.ibict.br/',url:q=>`https://bdtd.ibict.br/vufind/Search/Results?lookfor=${encodeURIComponent(q)}&type=AllFields`,descricao:'Teses e dissertações brasileiras sobre linguística e educação.'},
 {id:'tatoeba',nome:'Tatoeba',modo:'tatoeba',escopo:'geral',home:'https://tatoeba.org/',descricao:'Frases, traduções, transcrições e áudios.'},
 {id:'panlex',nome:'PanLex',modo:'portal',escopo:'geral',home:'https://panlex.org/',descricao:'Vocabulário e traduções entre milhares de variedades linguísticas.'},
 {id:'wiktionary',nome:'Wikcionário / Wiktionary',modo:'wiktionary',escopo:'geral',home:'https://pt.wiktionary.org/',descricao:'Definições, etimologia, flexões e traduções.'},
 {id:'lingualibre',nome:'Lingua Libre',modo:'lingualibre',escopo:'geral',home:'https://lingualibre.org/',descricao:'Gravações de pronúncia em centenas de línguas.'},
 {id:'fsi',nome:'FSI Language Courses',modo:'html',escopo:'geral',home:'https://www.fsi-language-courses.org/',url:()=>`https://www.fsi-language-courses.org/fsi-courses/`,descricao:'Cursos completos, apostilas e áudios de idiomas.'},
 {id:'dli',nome:'DLI GLOSS',modo:'portal',escopo:'geral',home:'https://gloss.dliflc.edu/',descricao:'Lições de leitura e escuta em muitos idiomas.'},
 {id:'merlot',nome:'MERLOT World Languages',modo:'html',escopo:'geral',home:'https://www.merlot.org/',url:q=>`https://www.merlot.org/merlot/materials.htm?keywords=${encodeURIComponent(q)}`,descricao:'Textbooks, workbooks e materiais educacionais.'},
 {id:'libretexts',nome:'LibreTexts',modo:'html',escopo:'geral',home:'https://commons.libretexts.org/',url:q=>`https://commons.libretexts.org/?search=${encodeURIComponent(q)}`,descricao:'Livros-texto e recursos educacionais abertos.'},
 {id:'elar',nome:'ELAR · Endangered Languages Archive',modo:'portal',escopo:'documentacao',home:'https://www.elararchive.org/',descricao:'Documentação de línguas ameaçadas.'},
 {id:'dobes',nome:'DOBES / The Language Archive',modo:'portal',escopo:'documentacao',home:'https://dobes.mpi.nl/',descricao:'Documentação multimídia de línguas ameaçadas.'},
 {id:'kaipuleohone',nome:'Kaipuleohone',modo:'html',escopo:'documentacao',home:'https://scholarspace.manoa.hawaii.edu/',url:q=>`https://scholarspace.manoa.hawaii.edu/search?query=${encodeURIComponent(q)}`,descricao:'Arquivo de línguas ameaçadas com áudio, vídeo e dicionários.'},
 {id:'corsal',nome:'CoRSAL',modo:'html',escopo:'sulasia',home:'https://digital.library.unt.edu/explore/collections/CORSAL/',url:q=>`https://digital.library.unt.edu/explore/collections/CORSAL/browse/?q=${encodeURIComponent(q)}`,descricao:'Documentação e recursos de línguas do Sul da Ásia.'},
 {id:'coerll',nome:'COERLL',modo:'html',escopo:'geral',home:'https://coerll.utexas.edu/coerll/',url:q=>`https://coerll.utexas.edu/coerll/?s=${encodeURIComponent(q)}`,descricao:'Cursos, gramáticas, livros abertos e currículos.'},
 {id:'oercommons',nome:'OER Commons',modo:'html',escopo:'geral',home:'https://oercommons.org/',url:q=>`https://oercommons.org/search?f.search=${encodeURIComponent(q)}`,descricao:'Cursos, módulos e materiais educacionais abertos.'},
 {id:'livelingua',nome:'Peace Corps / Live Lingua',modo:'html',escopo:'geral',home:'https://www.livelingua.com/project/peace-corps',url:()=>`https://www.livelingua.com/project/peace-corps`,descricao:'Apostilas e áudios de cursos do Peace Corps.'}
];
async function obter(url,opcoes={}){const r=await fetch(url,{...opcoes,headers:{'User-Agent':'BibliotecaLivre/2.3 (mailto:suporte@bibliotecalivre.org)',Accept:'*/*',...(opcoes.headers||{})},signal:AbortSignal.timeout(5500)});if(!r.ok)throw new Error(String(r.status));return r}
function fontesPara(q){const det=detectarIdioma(q);if(det.codigo&&!det.indigena)return{det,fontes:fontes.filter(f=>f.escopo==='geral'||(f.escopo==='sulasia'&&['hin','urd'].includes(det.codigo)))};if(det.indigena)return{det,fontes:fontes.filter(f=>f.escopo!=='sulasia')};return{det,fontes:fontes.filter(f=>f.modo!=='portal'||f.escopo==='geral')};}
async function buscarHtml(f,q,det){try{const consulta=det?.ingles&&det.nome&&semAcento(q)===semAcento(det.nome)?det.ingles:q,alvo=f.url(consulta),r=await obter(alvo),html=await r.text(),base=r.url||alvo,termos=termosBusca(q,det),vistos=new Set(),itens=[];const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&itens.length<8){const titulo=textoHtml(m[2]);if(titulo.length<4||titulo.length>200)continue;const n=semAcento(titulo);if(termos.length&&!termos.some(t=>n.includes(t)))continue;const url=seguroUrl(m[1],base);if(!url||vistos.has(url)||url===f.home)continue;if(/login|cadastro|contato|privacy|privacidade|menu|facebook|instagram|twitter|youtube|cookie|termos de uso/i.test(titulo))continue;vistos.add(url);itens.push({id:`${f.id}:${Buffer.from(url).toString('base64url').slice(0,36)}`,fonte:f.id,provedor:f.nome,titulo,descricao:f.descricao,tipo:tipos(titulo+' '+url),url,modo:'catalogo',idioma:det?.codigo||'',audio:null})}return itens}catch{return[]}}
async function buscarTatoeba(f,q,det){if(!det.codigo)return[];try{const u=new URL('https://api.tatoeba.org/v1/sentences');u.searchParams.set('lang',det.codigo);if(det.termo)u.searchParams.set('q',det.termo);u.searchParams.set('limit','10');u.searchParams.set('showtrans','all');u.searchParams.set('include','audios,transcriptions');u.searchParams.set('is_unapproved','no');const d=await(await obter(u)).json(),itens=Array.isArray(d?.data)?d.data:Array.isArray(d?.results)?d.results:[];return itens.map(s=>{const trans=[];const empilhar=v=>{if(Array.isArray(v))v.forEach(empilhar);else if(v&&typeof v==='object'&&v.text)trans.push(v.text)};empilhar(s.translations);const audio=Array.isArray(s.audios)&&s.audios[0]?.id?`https://api.tatoeba.org/v1/audios/${s.audios[0].id}/file`:null;return{id:`tatoeba:${s.id}`,fonte:'tatoeba',provedor:f.nome,titulo:s.text||`Frase ${s.id}`,descricao:trans.slice(0,3).join(' · ')||f.descricao,tipo:audio?'Frase + tradução + áudio':'Frase + tradução',url:`https://tatoeba.org/pt-br/sentences/show/${s.id}`,modo:'api',idioma:s.lang||det.codigo,audio}}).filter(x=>x.titulo)}catch{return[]}}
async function buscarWiktionary(f,q,det){try{const termo=det?.ingles&&det.nome&&semAcento(q)===semAcento(det.nome)?`${q} OR ${det.ingles}`:q,bases=[['pt','https://pt.wiktionary.org/w/api.php'],['en','https://en.wiktionary.org/w/api.php']],respostas=await Promise.all(bases.map(async([lang,base])=>{const u=new URL(base);for(const [k,v] of Object.entries({action:'query',list:'search',srsearch:termo,srlimit:'8',srprop:'snippet',format:'json',origin:'*'}))u.searchParams.set(k,v);const d=await(await obter(u)).json();return(d?.query?.search||[]).map(x=>({id:`wiktionary:${lang}:${x.pageid}`,fonte:'wiktionary',provedor:lang==='pt'?'Wikcionário':'Wiktionary',titulo:x.title,descricao:textoHtml(x.snippet)||f.descricao,tipo:'Dicionário / vocabulário',url:`https://${lang}.wiktionary.org/wiki/${encodeURIComponent(x.title.replace(/ /g,'_'))}`,modo:'api',idioma:det?.codigo||'',audio:null}))}));return respostas.flat().slice(0,12)}catch{return[]}}
async function buscarLinguaLibre(f,q,det){if(!det.codigo)return[];try{const criar=async categoria=>{const u=new URL('https://commons.wikimedia.org/w/api.php');u.searchParams.set('action','query');u.searchParams.set('format','json');u.searchParams.set('origin','*');u.searchParams.set('prop','imageinfo');u.searchParams.set('iiprop','url|extmetadata');if(categoria){u.searchParams.set('generator','categorymembers');u.searchParams.set('gcmtitle',`Category:Lingua Libre pronunciation-${det.codigo}`);u.searchParams.set('gcmtype','file');u.searchParams.set('gcmlimit','10')}else{u.searchParams.set('generator','search');u.searchParams.set('gsrsearch',`${det.ingles||q} Lingua Libre pronunciation`);u.searchParams.set('gsrnamespace','6');u.searchParams.set('gsrlimit','10')}const d=await(await obter(u)).json();return Object.values(d?.query?.pages||{})};let paginas=await criar(true);if(!paginas.length)paginas=await criar(false);return paginas.map(p=>{const info=p.imageinfo?.[0]||{},titulo=String(p.title||'').replace(/^File:/,'').replace(/\.(wav|ogg|mp3|flac)$/i,'');return{id:`lingualibre:${p.pageid}`,fonte:'lingualibre',provedor:f.nome,titulo,descricao:`Pronúncia · ${det.nome||q}`,tipo:'Áudio / pronúncia',url:info.descriptionurl||`https://commons.wikimedia.org/?curid=${p.pageid}`,modo:'api',idioma:det.codigo,audio:info.url||null}}).filter(x=>x.titulo)}catch{return[]}}
async function consultar(f,q,det){if(f.modo==='tatoeba')return buscarTatoeba(f,q,det);if(f.modo==='wiktionary')return buscarWiktionary(f,q,det);if(f.modo==='lingualibre')return buscarLinguaLibre(f,q,det);if(f.modo==='html')return buscarHtml(f,q,det);return[]}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({erro:'Método não permitido.'});const q=limpar(req.query.q);if(!q)return res.status(400).json({erro:'Consulta obrigatória.'});const selecao=fontesPara(q),ativas=selecao.fontes,tarefas=await Promise.all(ativas.map(async f=>{try{return{fonte:f,resultados:await consultar(f,q,selecao.det),erro:false}}catch{return{fonte:f,resultados:[],erro:true}}}));const resultados=[],porFonte={};for(const f of fontes)porFonte[f.id]={nome:f.nome,quantidade:0,portal:f.modo==='portal',consultada:ativas.some(a=>a.id===f.id),erro:false};for(const t of tarefas){resultados.push(...t.resultados);porFonte[t.fonte.id]={nome:t.fonte.nome,quantidade:t.resultados.length,portal:t.fonte.modo==='portal',consultada:true,erro:t.erro}}res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=1200');return res.status(200).json({ok:true,consulta:q,fontesTotal:fontes.length,fontesConsultadas:ativas.length,resultados,porFonte});}
