const limpar=v=>String(v||'').replace(/[<>\u0000-\u001f]/g,' ').replace(/\s+/g,' ').trim().slice(0,160);
const semAcento=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const textoHtml=v=>String(v||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/\s+/g,' ').trim();
const seguroUrl=(valor,base)=>{try{const u=new URL(valor,base);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}};
const tipos=t=>{const s=semAcento(t);if(/gramat|grammar/.test(s))return'Gramática';if(/dicion|dictionary|lexicon|vocab/.test(s))return'Dicionário / vocabulário';if(/cartilha|workbook|apostila|textbook|manual|livro|book/.test(s))return'Livro / apostila';if(/curso|course|curriculum|lesson|licao|exercise/.test(s))return'Curso / lição';if(/audio|pronunciation|recording|gravac/.test(s))return'Áudio / pronúncia';if(/tese|thesis|dissert|paper|article|estudo/.test(s))return'Estudo / pesquisa';return'Recurso de idioma'};
const idiomas={
 'nheengatu':'yrl','lingua geral amazonica':'yrl','guarani':'grn','tupi antigo':'tpw','tupi':'tpw','tupinamba':'tpn','quechua':'que','quichua':'que','aymara':'aym','mapuche':'arn','mapudungun':'arn','xavante':'xav','yanomami':'guu','tikuna':'tca','ticuna':'tca','kaingang':'kgp','terena':'ter','baniwa':'bwi','kaxinawa':'cbs','huni kuin':'cbs','portugues':'por','português':'por','ingles':'eng','inglês':'eng','espanhol':'spa','frances':'fra','francês':'fra','alemao':'deu','alemão':'deu','italiano':'ita','japones':'jpn','japonês':'jpn','mandarim':'cmn','chines':'cmn','chinês':'cmn','coreano':'kor','arabe':'ara','árabe':'ara','russo':'rus','hindi':'hin','urdu':'urd','persa':'pes','turco':'tur','latim':'lat','grego':'ell','hebraico':'heb','swahili':'swa','suaili':'swa','ioruba':'yor','yoruba':'yor','hausa':'hau','tagalog':'tgl','tailandes':'tha','tailandês':'tha','vietnamita':'vie','cherokee':'chr','navajo':'nav','lakota':'lkt','ojibwe':'oji'
};
function detectarIdioma(q){const n=semAcento(q);const chaves=Object.keys(idiomas).sort((a,b)=>b.length-a.length);for(const nome of chaves){const alvo=semAcento(nome);if(new RegExp(`(^|\\b)${alvo.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}(\\b|$)`,'i').test(n)){const termo=n.replace(alvo,' ').replace(/\s+/g,' ').trim();return{codigo:idiomas[nome],nome,termo}}}return{codigo:null,nome:null,termo:q}}
const fontes=[
 {id:'curt',nome:'Biblioteca Digital Curt Nimuendajú',modo:'html',home:'https://www.etnolinguistica.org/',url:q=>`https://www.etnolinguistica.org/search:site/q/${encodeURIComponent(q)}`,descricao:'Livros, gramáticas, cartilhas, dicionários e documentação de línguas indígenas sul-americanas.'},
 {id:'museu',nome:'Museu Nacional dos Povos Indígenas',modo:'html',home:'https://www.gov.br/museudoindio/',url:q=>`https://www.gov.br/museudoindio/pt-br/search?SearchableText=${encodeURIComponent(q)}`,descricao:'Publicações, acervos e materiais oficiais sobre povos e línguas indígenas.'},
 {id:'isa',nome:'Instituto Socioambiental · ISA',modo:'html',home:'https://acervo.socioambiental.org/',url:q=>`https://acervo.socioambiental.org/acervo?search_api_fulltext=${encodeURIComponent(q)}`,descricao:'Livros, estudos, relatórios e documentos sobre povos, culturas e línguas indígenas.'},
 {id:'ailla',nome:'AILLA',modo:'portal',home:'https://ailla.utexas.org/',descricao:'Archive of the Indigenous Languages of Latin America: áudio, vídeo, textos e documentação linguística.'},
 {id:'olac',nome:'OLAC',modo:'html',home:'https://www.language-archives.org/',url:q=>`https://search.language-archives.org/search.html?q=${encodeURIComponent(q)}`,descricao:'Agregador mundial de arquivos e recursos linguísticos.'},
 {id:'bdtd',nome:'BDTD / IBICT',modo:'html',home:'https://bdtd.ibict.br/',url:q=>`https://bdtd.ibict.br/vufind/Search/Results?lookfor=${encodeURIComponent(q)}&type=AllFields`,descricao:'Teses e dissertações brasileiras, inclusive linguística e educação indígena.'},
 {id:'tatoeba',nome:'Tatoeba',modo:'tatoeba',home:'https://tatoeba.org/',descricao:'Frases, traduções, transcrições e áudios em muitos idiomas.'},
 {id:'panlex',nome:'PanLex',modo:'portal',home:'https://panlex.org/',descricao:'Base lexical massiva para traduções e vocabulário entre milhares de variedades linguísticas.'},
 {id:'wiktionary',nome:'Wikcionário / Wiktionary',modo:'wiktionary',home:'https://pt.wiktionary.org/',descricao:'Definições, etimologia, flexões, traduções e vocabulário.'},
 {id:'lingualibre',nome:'Lingua Libre',modo:'lingualibre',home:'https://lingualibre.org/',descricao:'Gravações de pronúncia produzidas por falantes de centenas de línguas.'},
 {id:'fsi',nome:'FSI Language Courses',modo:'html',home:'https://www.fsi-language-courses.org/',url:()=>`https://www.fsi-language-courses.org/fsi-courses/`,descricao:'Cursos completos, apostilas e áudios de idiomas.'},
 {id:'dli',nome:'DLI GLOSS',modo:'portal',home:'https://gloss.dliflc.edu/',descricao:'Lições de leitura e escuta para dezenas de idiomas e níveis.'},
 {id:'merlot',nome:'MERLOT World Languages',modo:'html',home:'https://www.merlot.org/',url:q=>`https://www.merlot.org/merlot/materials.htm?keywords=${encodeURIComponent(q)}`,descricao:'Textbooks, workbooks e materiais educacionais de idiomas.'},
 {id:'libretexts',nome:'LibreTexts',modo:'html',home:'https://commons.libretexts.org/',url:q=>`https://commons.libretexts.org/?search=${encodeURIComponent(q)}`,descricao:'Livros-texto e recursos educacionais abertos.'},
 {id:'elar',nome:'ELAR · Endangered Languages Archive',modo:'portal',home:'https://www.elararchive.org/',descricao:'Documentação de línguas ameaçadas com áudio, vídeo, textos e transcrições.'},
 {id:'dobes',nome:'DOBES / The Language Archive',modo:'portal',home:'https://dobes.mpi.nl/',descricao:'Documentação multimídia de línguas ameaçadas de várias regiões do mundo.'},
 {id:'kaipuleohone',nome:'Kaipuleohone',modo:'html',home:'https://scholarspace.manoa.hawaii.edu/',url:q=>`https://scholarspace.manoa.hawaii.edu/search?query=${encodeURIComponent(q)}`,descricao:'Arquivo de línguas ameaçadas com áudio, vídeo, dicionários e anotações.'},
 {id:'corsal',nome:'CoRSAL',modo:'html',home:'https://digital.library.unt.edu/explore/collections/CORSAL/',url:q=>`https://digital.library.unt.edu/explore/collections/CORSAL/browse/?q=${encodeURIComponent(q)}`,descricao:'Recursos computacionais e documentação de línguas do Sul da Ásia.'},
 {id:'coerll',nome:'COERLL',modo:'html',home:'https://coerll.utexas.edu/coerll/',url:q=>`https://coerll.utexas.edu/coerll/?s=${encodeURIComponent(q)}`,descricao:'Cursos, gramáticas, livros abertos e currículos para aprender idiomas.'},
 {id:'oercommons',nome:'OER Commons',modo:'html',home:'https://oercommons.org/',url:q=>`https://oercommons.org/search?f.search=${encodeURIComponent(q)}`,descricao:'Recursos educacionais abertos, cursos, módulos e materiais de idiomas.'},
 {id:'livelingua',nome:'Peace Corps / Live Lingua',modo:'html',home:'https://www.livelingua.com/project/peace-corps',url:()=>`https://www.livelingua.com/project/peace-corps`,descricao:'Apostilas e áudios de cursos do Peace Corps, inclusive idiomas menos difundidos.'}
];
function resultadoPortal(f,q){const url=f.url?f.url(q):f.home;return{id:`${f.id}:portal:${semAcento(q)}`,fonte:f.id,provedor:f.nome,titulo:`Pesquisar “${q}” em ${f.nome}`,descricao:f.descricao,tipo:'Catálogo especializado',url,modo:'portal',idioma:'',audio:null}}
async function obter(url,opcoes={}){const r=await fetch(url,{...opcoes,headers:{'User-Agent':'BibliotecaLivre/2.2 (mailto:suporte@bibliotecalivre.org)',Accept:'*/*',...(opcoes.headers||{})},signal:AbortSignal.timeout(4800)});if(!r.ok)throw new Error(String(r.status));return r}
async function buscarHtml(f,q){try{const alvo=f.url(q),r=await obter(alvo),html=await r.text(),base=r.url||alvo,termos=semAcento(q).split(/\s+/).filter(x=>x.length>=3),vistos=new Set(),itens=[];const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&itens.length<6){const titulo=textoHtml(m[2]);if(titulo.length<4||titulo.length>180)continue;const n=semAcento(titulo);if(termos.length&&!termos.some(t=>n.includes(t)))continue;const url=seguroUrl(m[1],base);if(!url||vistos.has(url)||url===f.home)continue;if(/login|cadastro|contato|privacy|privacidade|menu|facebook|instagram|twitter|youtube/i.test(titulo))continue;vistos.add(url);itens.push({id:`${f.id}:${Buffer.from(url).toString('base64url').slice(0,32)}`,fonte:f.id,provedor:f.nome,titulo,descricao:f.descricao,tipo:tipos(titulo+' '+url),url,modo:'catalogo',idioma:'',audio:null})}return itens.length?itens:[resultadoPortal(f,q)]}catch{return[resultadoPortal(f,q)]}}
async function buscarTatoeba(f,q){const det=detectarIdioma(q);if(!det.codigo)return[resultadoPortal(f,q)];try{const u=new URL('https://api.tatoeba.org/v1/sentences');u.searchParams.set('lang',det.codigo);if(det.termo)u.searchParams.set('q',det.termo);u.searchParams.set('limit','8');u.searchParams.set('showtrans','all');u.searchParams.set('include','audios,transcriptions');u.searchParams.set('is_unapproved','no');const d=await(await obter(u)).json(),itens=Array.isArray(d?.data)?d.data:[];return itens.map(s=>{const trans=[];const empilhar=v=>{if(Array.isArray(v))v.forEach(empilhar);else if(v&&typeof v==='object'&&v.text)trans.push(v.text)};empilhar(s.translations);const audio=Array.isArray(s.audios)&&s.audios[0]?.id?`https://api.tatoeba.org/v1/audios/${s.audios[0].id}/file`:null;return{id:`tatoeba:${s.id}`,fonte:'tatoeba',provedor:f.nome,titulo:s.text||`Frase ${s.id}`,descricao:trans.slice(0,3).join(' · ')||f.descricao,tipo:audio?'Frase + tradução + áudio':'Frase + tradução',url:`https://tatoeba.org/pt-br/sentences/show/${s.id}`,modo:'api',idioma:s.lang||det.codigo,audio}}).filter(x=>x.titulo)}catch{return[resultadoPortal(f,q)]}}
async function buscarWiktionary(f,q){try{const bases=[['pt','https://pt.wiktionary.org/w/api.php'],['en','https://en.wiktionary.org/w/api.php']],respostas=await Promise.all(bases.map(async([lang,base])=>{const u=new URL(base);for(const [k,v] of Object.entries({action:'query',list:'search',srsearch:q,srlimit:'6',srprop:'snippet',format:'json',origin:'*'}))u.searchParams.set(k,v);const d=await(await obter(u)).json();return(d?.query?.search||[]).map(x=>({id:`wiktionary:${lang}:${x.pageid}`,fonte:'wiktionary',provedor:lang==='pt'?'Wikcionário':'Wiktionary',titulo:x.title,descricao:textoHtml(x.snippet)||f.descricao,tipo:'Dicionário / vocabulário',url:`https://${lang}.wiktionary.org/wiki/${encodeURIComponent(x.title.replace(/ /g,'_'))}`,modo:'api',idioma:'',audio:null}))}));return respostas.flat().slice(0,10)}catch{return[resultadoPortal(f,q)]}}
async function buscarLinguaLibre(f,q){const det=detectarIdioma(q);try{const u=new URL('https://commons.wikimedia.org/w/api.php');u.searchParams.set('action','query');u.searchParams.set('format','json');u.searchParams.set('origin','*');u.searchParams.set('prop','imageinfo');u.searchParams.set('iiprop','url|extmetadata');if(det.codigo){u.searchParams.set('generator','categorymembers');u.searchParams.set('gcmtitle',`Category:Lingua Libre pronunciation-${det.codigo}`);u.searchParams.set('gcmtype','file');u.searchParams.set('gcmlimit','8')}else{u.searchParams.set('generator','search');u.searchParams.set('gsrsearch',`${q} Lingua Libre`);u.searchParams.set('gsrnamespace','6');u.searchParams.set('gsrlimit','8')}const d=await(await obter(u)).json(),paginas=Object.values(d?.query?.pages||{});const itens=paginas.map(p=>{const info=p.imageinfo?.[0]||{},titulo=String(p.title||'').replace(/^File:/,'').replace(/\.(wav|ogg|mp3|flac)$/i,'');return{id:`lingualibre:${p.pageid}`,fonte:'lingualibre',provedor:f.nome,titulo,descricao:`Pronúncia${det.nome?` · ${det.nome}`:''}`,tipo:'Áudio / pronúncia',url:info.descriptionurl||`https://commons.wikimedia.org/?curid=${p.pageid}`,modo:'api',idioma:det.codigo||'',audio:info.url||null}}).filter(x=>x.titulo);return itens.length?itens:[resultadoPortal(f,q)]}catch{return[resultadoPortal(f,q)]}}
async function consultar(f,q){if(f.modo==='tatoeba')return buscarTatoeba(f,q);if(f.modo==='wiktionary')return buscarWiktionary(f,q);if(f.modo==='lingualibre')return buscarLinguaLibre(f,q);if(f.modo==='html')return buscarHtml(f,q);return[resultadoPortal(f,q)]}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({erro:'Método não permitido.'});const q=limpar(req.query.q);if(!q)return res.status(400).json({erro:'Consulta obrigatória.'});const tarefas=await Promise.all(fontes.map(async f=>{try{const resultados=await consultar(f,q);return{fonte:f,resultados,erro:false}}catch{return{fonte:f,resultados:[resultadoPortal(f,q)],erro:true}}}));const resultados=[],porFonte={};for(const t of tarefas){resultados.push(...t.resultados);porFonte[t.fonte.id]={nome:t.fonte.nome,quantidade:t.resultados.filter(x=>x.modo!=='portal').length,portal:t.resultados.every(x=>x.modo==='portal'),erro:t.erro}}res.setHeader('Cache-Control','s-maxage=600, stale-while-revalidate=1800');return res.status(200).json({ok:true,consulta:q,fontesTotal:fontes.length,fontesConsultadas:fontes.length,resultados,porFonte});}
